kind: pipeline
type: docker
name: blog

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    environment:
      rsa:
        from_secret: rsa
    commands:
      - mkdir ~/.ssh && cd ~/.ssh
      - pwd
      - echo $rsa
      - git clone https://github.com.cnpmjs.org/lim-mil/blog.git .
#    - git checkout $DRONE_COMMIT

  - name: backend
    pull: if-not-exists
    image: appleboy/drone-ssh:1.5.7
    settings:
      host: 10.0.12.10
      username: root
      password:
        from_secret: ssh_password
      port: 22
      script:
        - docker stop blog
        - docker container rm -f blog
        - docker image rm blog
        - cd /home/ubuntu/blog
        - docker build -t blog .
        - docker -d -p 127.0.0.1:7331:7331 --name blog blog
    when:
      branch: master

volumes:
  - name: data
    host:
      path: /data/drone/blog
