kind: pipeline
type: docker
name: blog

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    commands:
      - git config --global http.postBuffer 5242880000
      - git clone https://github.com.cnpmjs.org/lim-mil/blog.git .
#    - git checkout $DRONE_COMMIT

  - name: backend
    pull: if-not-exists
    image: appleboy/drone-ssh:1.5.7
    settings:
      host: 0.0.0.0
      username: root
      password:
        from_secret: ssh_password
      port: 22
      script:
        - docker stop blog
        - docker container rm -f blog
        - docker image rm blog
        - cd /home/ubuntu/blog
        - docker build -t blog .
        - docker -d -p 127.0.0.1:7331:7331 --name blog blog
    when:
      branch: master

volumes:
  - name: data
    host:
      path: /data/drone/blog
